# Generated by Django 3.2.5 on 2021-07-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='projectDelevery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
