# Generated by Django 3.2.5 on 2021-07-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_categorey_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorey',
            name='slug',
        ),
    ]
