# Generated by Django 3.2.5 on 2021-08-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_categorey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
