# Generated by Django 3.2.5 on 2021-08-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_email_contact_email_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/client/%Y/%m/%d')),
                ('site_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
