# Generated by Django 3.2.5 on 2021-08-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
